name: Consumer - Build/Deploy

# Reusable workflow to build, test and deploy the consumer images
# these images are not tested

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      image-name:
        required: true
        type: string
      scope:
        description: "The scope of the image if doing Matrix builds"
        required: false
        type: string
        default: "public"
      push: 
        description: "Whether to push the image to the registry"
        required: true
        type: boolean

env:
  TAG: ghcr.io/${{ inputs.image-name }}:v${{ inputs.version }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Image
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
        with:
          context: .
          file: base.Dockerfile
          build-args: |
            IDRIS_VERSION=${{ inputs.version }}
          cache-from: type=gha,scope=build-test-${{ inputs.scope }}
          cache-to: type=gha,mode=max,scope=build-test-${{ inputs.scope }}

  deploy:
    name: Deploy
    if: ${{ inputs.push }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Buildx
        uses: "./.github/actions/setup-buildx"
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.SSH_USER }}
          ssh_ip: ${{ secrets.SSH_IP }}

      - name: Login to GHCR
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: create-meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ inputs.image-name }}

      - name: Build and push
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          push: ${{ github.event_name == 'push' }}
          file: ${{ inputs.dockerfile }}
          build-args: |
            IDRIS_VERSION=${{ inputs.version }}
          tags: ${{ env.TAG }}
          labels: ${{ steps.create-meta.outputs.labels }}
          # When doing matrix builds, we need to scope the image
          # https://github.com/moby/buildkit/issues/2885
          cache-from: type=gha,scope=build-${{ inputs.scope }}
          cache-to: type=gha,mode=max,scope=build-${{ inputs.scope }}
