name: Deploy Docker Images

on:
  # manually deploy a specific
  # if version isn't specified, it will deploy nightly
  workflow_dispatch:
    inputs:
      version:
        description: Idris Version
        required: true
        default: "latest"
  # can we be more DRY here?
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy.yml" # this file
      - "*.Dockerfile"
      # single
      - ".github/actions/setup-buildx/action.yml"
      - ".github/workflows/build-and-deploy-single.yml"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/deploy.yml" # this file
      - "*.Dockerfile"
      # single
      - ".github/actions/setup-buildx/action.yml"
      - ".github/workflows/build-and-deploy-single.yml"

permissions:
  packages: write
  contents: read

jobs:
  # build the image for just AMD64, and use GHA cache to speed up test build later on
  # I could also upload the image as an artifact, but that's a lot of work. I'll see how this goes...
  base-single:
    name: Base Image Single
    if: ${{ github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/build-test-deploy-single.yml
    with:
      version: ${{ inputs.version }}
      dockerfile: base.Dockerfile
      image-name: ${{ github.repository }}/base
      scope: base-${{ inputs.version }}
      test: true
    secrets: inherit

  # consumers of the base image are devcontainer, ubuntu and debian images
  consumer-single:
    name: Consumer Image - ${{ matrix.consumer }}
    needs: base-single
    if: ${{ github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        consumer: [devcontainer, ubuntu, debian]
    uses: ./.github/workflows/build-test-deploy-single.yml
    with:
      version: ${{ inputs.version }}
      dockerfile: ${{ matrix.consumer }}.Dockerfile
      image-name: ${{ github.repository }}/${{ matrix.consumer }}
      scope: ${{ matrix.consumer }}
      test: false
    secrets: inherit

  base-matrix:
    name: Base Image - ${{ matrix.idris-version }}
    if: ${{ github.event_name != 'workflow_dispatch' }}
    strategy:
      matrix:
        idris-version: ["v0.5.0", "v0.5.1", "latest"]
    uses: ./.github/workflows/build-test-deploy-single.yml
    with:
      version: ${{ matrix.idris-version }}
      dockerfile: base.Dockerfile
      image-name: ${{ github.repository }}/base
      scope: ${{ matrix.idris-version }}
      test: true
    secrets: inherit

  consumer-matrix:
    name: Consumer Image - ${{ matrix.consumer }} ${{ matrix.idris-version }}
    needs: consumer-matrix
    if: ${{ github.event_name != 'workflow_dispatch' }}
    strategy:
      matrix:
        idris-version: ["v0.5.0", "v0.5.1", "latest"]
        consumer: [devcontainer, ubuntu, debian]
    uses: ./.github/workflows/build-test-deploy-single.yml
    with:
      version: ${{ matrix.idris-version }}
      dockerfile: ${{ matrix.consumer }}.Dockerfile
      image-name: ${{ github.repository }}/${{ matrix.consumer }}
      scope: ${{ matrix.consumer }}-${{ matrix.idris-version }}
    secrets: inherit
